@StoryforgeApi_HostAddress = http://localhost:5124

GET {{StoryforgeApi_HostAddress}}/storyList
GET {{StoryforgeApi_HostAddress}}/story/{id}
GET {{StoryforgeApi_HostAddress}}/getFreeId
POST {{StoryforgeApi_HostAddress}}/submitStory

Accept: application/json



###
